function RawDataS1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RAWDATAS1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  RAWDATAS1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RAWDATAS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RawDataS1 = importfile("/Users/penquin/Library/CloudStorage/OneDrive-KMITL/Project/Raw_Data.xlsx", "Fuel Consumption", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Oct-2023 22:50:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["RPM", "Torque", "B7", "B7WithCeO2_300DOCPt_300PDPF", "B100", "B100WithCeO2_300DOCPt_300PDPF"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify variable properties    
opts = setvaropts(opts, ["RPM", "Torque"], "EmptyFieldRule", "auto");

% Import the data
RawDataS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RawDataS1 = [RawDataS1; tb]; %#ok<AGROW>
end

end