function Nm = AVLGas(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  NM = IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  NM = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Var = AVLGas("/Users/penquin/Library/CloudStorage/OneDrive-KMITL/Project/DataBase/AVLGas for four cases/B7/1500, 84Nm.csv", [2, Inf])
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Nov-2023 09:44:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Number", "Times", "SpeedRPM", "DieselTimingCA", "TemperatureC", "N", "NMax", "k1m", "kMax1m", "COvol", "COcorrectedvol", "CO2vol", "HCppm", "HCcorrppm", "Dilution", "O2vol", "Lambda", "NOppm", "AmbientTemperatureC", "AirPressurembar"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["SpeedRPM", "DieselTimingCA", "TemperatureC"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SpeedRPM", "DieselTimingCA", "TemperatureC"], "EmptyFieldRule", "auto");

% Import the data
Nm = readtable(filename, opts);

end